export const dairyAndAlternatives: string[] = [
  // Dairy Products
  'Milk',
  'Cheese',
  'Yogurt',
  'Butter',
  'Cream',
  'Sour Cream',
  'Cottage Cheese',
  'Ricotta',
  'Ghee',
  'Kefir',
  'Greek Yogurt',
  'Heavy Cream',
  'Half-and-Half',
  'Cream Cheese',
  'Mascarpone',
  'Clotted Cream',
  'Buttermilk',
  'Paneer',
  'Evaporated Milk',
  'Condensed Milk',
  'Skim Milk',
  'Low-Fat Milk',
  'Whole Milk',

  // Dairy Alternatives
  'Almond Milk',
  'Soy Milk',
  'Oat Milk',
  'Coconut Milk',
  'Rice Milk',
  'Cashew Milk',
  'Hemp Milk',
  'Macadamia Milk',
  'Pea Milk',
  'Flax Milk',
  'Coconut Yogurt',
  'Almond Yogurt',
  'Soy Yogurt',
  'Oat Yogurt',
  'Cashew Cheese',
  'Vegan Cheese',
  'Nut-Based Cheese',
  'Coconut Cream',
  'Silken Tofu',
  'Firm Tofu',
  'Tempeh',
]
