export const miscellaneous: string[] = [
  'Tofu',
  'Tempeh',
  'Seitan',
  'Miso',
  'Tahini',
  'Hummus',
  'Nutritional Yeast',
  'Textured Vegetable Protein',
  'Protein Powder',
  'Seaweed',
  'Spirulina',
  'Chlorella',
  'Aloe Vera',
  'Kimchi',
  'Sauerkraut',
  'Pickles',
  'Olives',
  'Capers',
  'Vinegar',
  'Soy Sauce',
  'Tamari',
  'Fish Sauce',
  'Worcestershire Sauce',
  'Hot Sauce',
  'BBQ Sauce',
  'Mustard',
  'Ketchup',
  'Mayonnaise',
  'Salad Dressing',
  'Pesto',
  'Tomato Paste',
  'Tomato Sauce',
  'Salsa',
  'Guacamole',
  'Relish',
  'Marinara Sauce',
  'Tartar Sauce',
  'Chutney',
  'Jam',
  'Jelly',
  'Peanut Butter',
  'Almond Butter',
  'Cashew Butter',
  'Sunflower Seed Butter',
  'Honey',
  'Maple Syrup',
  'Molasses',
  'Agave Nectar',
  'Rice Syrup',
  'Corn Syrup',
  'Gelatin',
  'Agar-Agar',
  'Pectin',
  'Xanthan Gum',
  'Guar Gum',
  'Baking Soda',
  'Baking Powder',
  'Cornstarch',
  'Arrowroot',
  'Tapioca Starch',
  'Potato Starch',
  'Vital Wheat Gluten',
  'Yeast',
  'Active Dry Yeast',
  'Instant Yeast',
  'Fresh Yeast',
  'Rice Paper',
  'Nori',
  'Wonton Wrappers',
  'Spring Roll Wrappers',
]
